// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKJMaUH2wyE6-ywT1DAOD39vFy4wD8TlE',
    appId: '1:296013157420:web:79512477f4440aff5aed89',
    messagingSenderId: '296013157420',
    projectId: 'jembe-talk',
    authDomain: 'jembe-talk.firebaseapp.com',
    storageBucket: 'jembe-talk.firebasestorage.app',
    measurementId: 'G-5MLMZP43MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjOy1OTJoKg-Ts8QfCZm9cIWJRz5LXnS0',
    appId: '1:296013157420:android:5f7d20a6ab639c4e5aed89',
    messagingSenderId: '296013157420',
    projectId: 'jembe-talk',
    storageBucket: 'jembe-talk.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKnSxRxVzvjcSWncl_lK5oKBNZfsk9PFs',
    appId: '1:296013157420:ios:3d42b129386d34ed5aed89',
    messagingSenderId: '296013157420',
    projectId: 'jembe-talk',
    storageBucket: 'jembe-talk.firebasestorage.app',
    iosBundleId: 'com.example.jembeTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKnSxRxVzvjcSWncl_lK5oKBNZfsk9PFs',
    appId: '1:296013157420:ios:3d42b129386d34ed5aed89',
    messagingSenderId: '296013157420',
    projectId: 'jembe-talk',
    storageBucket: 'jembe-talk.firebasestorage.app',
    iosBundleId: 'com.example.jembeTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKJMaUH2wyE6-ywT1DAOD39vFy4wD8TlE',
    appId: '1:296013157420:web:dd41310f5e8876c95aed89',
    messagingSenderId: '296013157420',
    projectId: 'jembe-talk',
    authDomain: 'jembe-talk.firebaseapp.com',
    storageBucket: 'jembe-talk.firebasestorage.app',
    measurementId: 'G-3GBW3P8XBP',
  );
}
